name = "kaiten-cron"
main = "cron.js"
compatibility_date = "2024-11-05"

[triggers]
crons = [
  "01 15 * * *", "01 16 * * *", "01 17 * * *", "01 18 * * *",
  "01 19 * * *", "01 20 * * *", "01 21 * * *", "01 22 * * *",
  "01 23 * * *"
]

# Привяжи те же ресурсы, что использует прод
[[d1_databases]]
binding = "DB"
database_name = "<kaiten-db>"
database_id   = "<f7e15480-2d44-4d39-af6a-95209477aaf1>"


