name = "kaiten-cron"
main = "cron.js"
compatibility_date = "2024-11-05"

[triggers]
crons = [
  "58 14 * * *", "58 15 * * *", "58 16 * * *", "58 17 * * *",
  "58 18 * * *", "58 19 * * *", "58 20 * * *", "58 21 * * *",
  "58 22 * * *", "58 23 * * *"
]

# Привяжи те же ресурсы, что использует прод
[[d1_databases]]
binding = "DB"
database_name = "<kaiten-db>"
database_id   = "<f7e15480-2d44-4d39-af6a-95209477aaf1>"


